-- Supabase Seed Data
-- This file contains sample data for development/testing

-- Note: The actual schema is defined in schema.sql
-- Run: psql -f schema.sql first, then this file

-- Insert sample papers for testing (without embeddings - those are generated by the harvester)
INSERT INTO forge_papers (
    arxiv_id,
    title,
    authors,
    abstract,
    pdf_url,
    year,
    source,
    status
) VALUES (
    '1706.03762',
    'Attention Is All You Need',
    ARRAY['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit', 'Llion Jones', 'Aidan N. Gomez', 'Lukasz Kaiser', 'Illia Polosukhin'],
    'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
    'https://arxiv.org/pdf/1706.03762.pdf',
    2017,
    'arxiv',
    'pending'
) ON CONFLICT (arxiv_id) DO NOTHING;

-- Insert sample opportunity for testing (linked to the paper above)
-- Note: In production, this would be created by the analysis pipeline
INSERT INTO forge_opportunities (
    paper_id,
    analyst_summary,
    architect_design,
    strategist_plan,
    nova_score,
    analysis_status
)
SELECT
    id,
    '{
        "paperAnalysis": {
            "introOverview": "The Transformer architecture revolutionized NLP by replacing recurrence with attention.",
            "summary": "Introduces multi-head self-attention mechanism enabling parallelization.",
            "researchProblem": "Sequential computation in RNNs is slow and hard to parallelize.",
            "methodInPlainEnglish": "Uses attention to weigh input tokens, processing all positions simultaneously.",
            "coreBreakthrough": "Self-attention mechanism that models relationships without sequential processing.",
            "keyInnovations": ["Multi-head attention", "Positional encoding"],
            "evidence": ["Achieved SOTA on WMT 2014"],
            "limitations": ["Quadratic complexity with sequence length"]
        }
    }'::jsonb,
    '{
        "opportunities": [
            {
                "name": "Transformer-as-a-Service API",
                "type": "api_plugin",
                "oneLiner": "Custom transformer models via API",
                "coreValue": "Deploy custom attention-based models",
                "targetUser": "NLP developers",
                "whyNow": "Transformer adoption accelerating",
                "buildComplexity": "Medium"
            }
        ],
        "recommendedPath": "Transformer-as-a-Service API",
        "recommendationReason": "High demand for custom transformer implementations"
    }'::jsonb,
    '{
        "strategy": {
            "mvpScope": "Core transformer API with 3 model sizes",
            "unfairAdvantage": "Direct implementation from original research",
            "competitors": [{"name": "Hugging Face", "url": "https://huggingface.co", "differentiation": "Research-native implementation"}],
            "marketVerdict": "High competition but growing market",
            "gtmPath": "Target research labs and startups",
            "pricingModel": "Pay-per-token API"
        }
    }'::jsonb,
    85,
    'completed'
FROM forge_papers
WHERE arxiv_id = '1706.03762'
ON CONFLICT (paper_id) DO NOTHING;
